version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: testdb
    volumes:
      - ./DDL/create_tables.sql:/docker-entrypoint-initdb.d/init.sql




